template_path: remote-templates/AccountAlertTopics.yaml
stack_name: AccountAlertTopics
dependencies:
  - bootstrap
parameters:
  pAccountDescription: bridge-{{ environment_variable.TRAVIS_BRANCH }}
  pInitialSubscriberEmail: {{ environment_variable.OperatorEmail_prod }}
  pEnableSubscriberSMS: "false"
  pBillingThreshold: "1000"
  pDeployLambda: "true"
  pLambdaFunctionName: "infra-notices"
  pSlackWebhookURL: {{ environment_variable.SlackWebhookUrl_prod }}
  pSlackChannel: "#infra-notices"
hooks:
  before_update:
    - !cmd "aws --profile {{ var.profile }} s3 cp s3://{{ environment_variable.AdminCentralInfraCfBucket }}/aws-infra/master/AccountAlertTopics.yaml ./remote-templates/AccountAlertTopics.yaml"
