template_path: remote/vpc.yaml
stack_name: BridgeServer2-vpc
dependencies:
  - prod/bootstrap.yaml
parameters:
  VpcName: BridgeServer2-vpc
  VpcSubnetPrefix: "172.32"
hooks:
  before_create:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/vpc.yaml --create-dirs -o templates/remote/vpc.yaml"
  before_update:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/vpc.yaml --create-dirs -o templates/remote/vpc.yaml"
