Description: Resources for Jumpcloud IDP
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  BridgeprodAdminMetadata:
    Type: String
    Description: "Public certificate for Jumpcloud AWS bridgeprod-admin app"
  BridgeprodDeveloperMetadata:
    Type: String
    Description: "Public certificate for Jumpcloud AWS bridgeprod-developer app"
  BridgeprodiOSDeveloperMetadata:
    Type: String
    Description: "Public certificate for Jumpcloud AWS bridgeprod-ios-developer app"
  BridgeprodInternMetadata:
    Type: String
    Description: "Public certificate for Jumpcloud AWS bridgeprod-intern app"
Resources:
  BridgeprodAdminSamlProvider:
    Type: Custom::SAMLProvider
    Properties:
      ServiceToken: !ImportValue
        'Fn::Sub': '${AWS::Region}-cfn-cr-saml-provider-FunctionArn'
      Name: "bridgeprod-admin"
      Metadata: !Ref BridgeprodAdminMetadata
      URL: ""
  BridgeprodAdminSamlProviderRole:
    Type: AWS::IAM::Role
    Properties:
      MaxSessionDuration: 28800
      RoleName: !GetAtt BridgeprodAdminSamlProvider.Name
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref BridgeprodAdminSamlProvider
            Action: sts:AssumeRoleWithSAML
            Condition:
              StringEquals:
                "SAML:aud": "https://signin.aws.amazon.com/saml"
  BridgeprodDeveloperSamlProvider:
    Type: Custom::SAMLProvider
    Properties:
      ServiceToken: !ImportValue
        'Fn::Sub': '${AWS::Region}-cfn-cr-saml-provider-FunctionArn'
      Name: "bridgeprod-developer"
      Metadata: !Ref BridgeprodDeveloperMetadata
      URL: ""
  BridgeprodDeveloperSamlProviderRole:
    Type: AWS::IAM::Role
    Properties:
      MaxSessionDuration: 28800
      RoleName: !GetAtt BridgeprodDeveloperSamlProvider.Name
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/PowerUserAccess
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref BridgeprodDeveloperSamlProvider
            Action: sts:AssumeRoleWithSAML
            Condition:
              StringEquals:
                "SAML:aud": "https://signin.aws.amazon.com/saml"
  BridgedprodiOSDeveloperSamlProvider:
    Type: Custom::SAMLProvider
    Properties:
      ServiceToken: !ImportValue
        'Fn::Sub': '${AWS::Region}-cfn-cr-saml-provider-FunctionArn'
      Name: "bridgeprod-ios-developer"
      Metadata: !Ref BridgeprodiOSDeveloperMetadata
      URL: ""
  BridgedprodiOSDeveloperSamlProviderRole:
    Type: AWS::IAM::Role
    Properties:
      MaxSessionDuration: 28800
      RoleName: !GetAtt BridgedprodiOSDeveloperSamlProvider.Name
      ManagedPolicyArns:
        - 'Fn::ImportValue': !Sub '${AWS::Region}-iam-policies-iOSBucketManagedPolicyArn'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref BridgedprodiOSDeveloperSamlProvider
            Action: sts:AssumeRoleWithSAML
            Condition:
              StringEquals:
                "SAML:aud": "https://signin.aws.amazon.com/saml"
  BridgeprodInternSamlProvider:
    Type: Custom::SAMLProvider
    Properties:
      ServiceToken: !ImportValue
        'Fn::Sub': '${AWS::Region}-cfn-cr-saml-provider-FunctionArn'
      Name: "bridgeprod-intern"
      Metadata: !Ref BridgeprodInternMetadata
      URL: ""
  BridgeprodInternSamlProviderRole:
    Type: AWS::IAM::Role
    Properties:
      MaxSessionDuration: 28800
      RoleName: !GetAtt BridgeprodInternSamlProvider.Name
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref BridgeprodInternSamlProvider
            Action: sts:AssumeRoleWithSAML
            Condition:
              StringEquals:
                "SAML:aud": "https://signin.aws.amazon.com/saml"
Outputs:
  BridgeprodAdminSamlProviderArn:
    Value: !Ref BridgeprodAdminSamlProvider
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-BridgeprodAdminSamlProviderArn'
  BridgeprodAdminSamlProviderRoleArn:
    Value: !GetAtt BridgeprodAdminSamlProviderRole.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-BridgeprodAdminSamlProviderRoleArn'
  BridgeprodDeveloperSamlProviderArn:
    Value: !Ref BridgeprodDeveloperSamlProvider
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-BridgeprodDeveloperSamlProviderArn'
  BridgeprodDeveloperSamlProviderRoleArn:
    Value: !GetAtt BridgeprodDeveloperSamlProviderRole.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-BridgeprodDeveloperSamlProviderRoleArn'
  BridgedprodiOSDeveloperSamlProviderArn:
    Value: !Ref BridgedprodiOSDeveloperSamlProvider
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-BridgedprodiOSDeveloperSamlProviderArn'
  BridgedprodiOSDeveloperSamlProviderRoleArn:
    Value: !GetAtt BridgedprodiOSDeveloperSamlProviderRole.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-BridgedprodiOSDeveloperSamlProviderRoleArn'
  BridgeprodInternSamlProviderArn:
    Value: !Ref BridgeprodInternSamlProvider
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-BridgeprodInternSamlProviderArn'
  BridgeprodInternSamlProviderRoleArn:
    Value: !GetAtt BridgeprodInternSamlProvider.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-BridgeprodInternSamlProviderRoleArn'
