template_path: remote/vpc.yaml
stack_name: bridge-aux
dependencies:
  - develop/bridge.yaml
parameters:
  VpcSubnetPrefix: "172.51"
  VpcName: bridge-aux
hooks:
  before_update:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/vpc.yaml --create-dirs -o templates/remote/vpc.yaml"
